### ISSUE TITLE
Should we deprecate this library?

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/scale-text#2]
According to libraries.io Nevergreen is the only project using this library.

https://libraries.io/npm/scale-text/usage

Given we haven't touched this project in over 2 years and Nevergreen has several issue raised about the Monitor page, does it make more sense to roll this code back into Nevergreen?

This seems like it would make fixing the Nevergreen issues easier, we could always port changes back to this library once we were happy.

Thoughts?

cc/ @joejag @cowley05

**Comment by joejag** [comment]
That's true. We haven't really made this a friendly API to use. Porting it back seems fine to me
